/* soapH.h
   Generated by gSOAP 2.7.10 from imRoot.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (87)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_ns3__updateServerInfo
#define SOAP_TYPE_ns3__updateServerInfo (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__updateServerInfo(struct soap*, struct ns3__updateServerInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__updateServerInfo(struct soap*, const struct ns3__updateServerInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__updateServerInfo(struct soap*, const struct ns3__updateServerInfo *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__updateServerInfo(struct soap*, const char*, int, const struct ns3__updateServerInfo *, const char*);
SOAP_FMAC3 struct ns3__updateServerInfo * SOAP_FMAC4 soap_get_ns3__updateServerInfo(struct soap*, struct ns3__updateServerInfo *, const char*, const char*);
SOAP_FMAC3 struct ns3__updateServerInfo * SOAP_FMAC4 soap_in_ns3__updateServerInfo(struct soap*, const char*, struct ns3__updateServerInfo *, const char*);

#ifndef SOAP_TYPE_ns3__updateServerInfoResponse
#define SOAP_TYPE_ns3__updateServerInfoResponse (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__updateServerInfoResponse(struct soap*, struct ns3__updateServerInfoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__updateServerInfoResponse(struct soap*, const struct ns3__updateServerInfoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__updateServerInfoResponse(struct soap*, const struct ns3__updateServerInfoResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__updateServerInfoResponse(struct soap*, const char*, int, const struct ns3__updateServerInfoResponse *, const char*);
SOAP_FMAC3 struct ns3__updateServerInfoResponse * SOAP_FMAC4 soap_get_ns3__updateServerInfoResponse(struct soap*, struct ns3__updateServerInfoResponse *, const char*, const char*);
SOAP_FMAC3 struct ns3__updateServerInfoResponse * SOAP_FMAC4 soap_in_ns3__updateServerInfoResponse(struct soap*, const char*, struct ns3__updateServerInfoResponse *, const char*);

#ifndef SOAP_TYPE_ns3__updateSysConf
#define SOAP_TYPE_ns3__updateSysConf (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__updateSysConf(struct soap*, struct ns3__updateSysConf *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__updateSysConf(struct soap*, const struct ns3__updateSysConf *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__updateSysConf(struct soap*, const struct ns3__updateSysConf *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__updateSysConf(struct soap*, const char*, int, const struct ns3__updateSysConf *, const char*);
SOAP_FMAC3 struct ns3__updateSysConf * SOAP_FMAC4 soap_get_ns3__updateSysConf(struct soap*, struct ns3__updateSysConf *, const char*, const char*);
SOAP_FMAC3 struct ns3__updateSysConf * SOAP_FMAC4 soap_in_ns3__updateSysConf(struct soap*, const char*, struct ns3__updateSysConf *, const char*);

#ifndef SOAP_TYPE_ns3__updateSysConfResponse
#define SOAP_TYPE_ns3__updateSysConfResponse (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__updateSysConfResponse(struct soap*, struct ns3__updateSysConfResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__updateSysConfResponse(struct soap*, const struct ns3__updateSysConfResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__updateSysConfResponse(struct soap*, const struct ns3__updateSysConfResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__updateSysConfResponse(struct soap*, const char*, int, const struct ns3__updateSysConfResponse *, const char*);
SOAP_FMAC3 struct ns3__updateSysConfResponse * SOAP_FMAC4 soap_get_ns3__updateSysConfResponse(struct soap*, struct ns3__updateSysConfResponse *, const char*, const char*);
SOAP_FMAC3 struct ns3__updateSysConfResponse * SOAP_FMAC4 soap_in_ns3__updateSysConfResponse(struct soap*, const char*, struct ns3__updateSysConfResponse *, const char*);

#ifndef SOAP_TYPE_ns3__setMileage
#define SOAP_TYPE_ns3__setMileage (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__setMileage(struct soap*, struct ns3__setMileage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__setMileage(struct soap*, const struct ns3__setMileage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__setMileage(struct soap*, const struct ns3__setMileage *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__setMileage(struct soap*, const char*, int, const struct ns3__setMileage *, const char*);
SOAP_FMAC3 struct ns3__setMileage * SOAP_FMAC4 soap_get_ns3__setMileage(struct soap*, struct ns3__setMileage *, const char*, const char*);
SOAP_FMAC3 struct ns3__setMileage * SOAP_FMAC4 soap_in_ns3__setMileage(struct soap*, const char*, struct ns3__setMileage *, const char*);

#ifndef SOAP_TYPE_ns3__setMileageResponse
#define SOAP_TYPE_ns3__setMileageResponse (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__setMileageResponse(struct soap*, struct ns3__setMileageResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__setMileageResponse(struct soap*, const struct ns3__setMileageResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__setMileageResponse(struct soap*, const struct ns3__setMileageResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__setMileageResponse(struct soap*, const char*, int, const struct ns3__setMileageResponse *, const char*);
SOAP_FMAC3 struct ns3__setMileageResponse * SOAP_FMAC4 soap_get_ns3__setMileageResponse(struct soap*, struct ns3__setMileageResponse *, const char*, const char*);
SOAP_FMAC3 struct ns3__setMileageResponse * SOAP_FMAC4 soap_in_ns3__setMileageResponse(struct soap*, const char*, struct ns3__setMileageResponse *, const char*);

#ifndef SOAP_TYPE_ns3__setGPSFrequency
#define SOAP_TYPE_ns3__setGPSFrequency (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__setGPSFrequency(struct soap*, struct ns3__setGPSFrequency *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__setGPSFrequency(struct soap*, const struct ns3__setGPSFrequency *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__setGPSFrequency(struct soap*, const struct ns3__setGPSFrequency *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__setGPSFrequency(struct soap*, const char*, int, const struct ns3__setGPSFrequency *, const char*);
SOAP_FMAC3 struct ns3__setGPSFrequency * SOAP_FMAC4 soap_get_ns3__setGPSFrequency(struct soap*, struct ns3__setGPSFrequency *, const char*, const char*);
SOAP_FMAC3 struct ns3__setGPSFrequency * SOAP_FMAC4 soap_in_ns3__setGPSFrequency(struct soap*, const char*, struct ns3__setGPSFrequency *, const char*);

#ifndef SOAP_TYPE_ns3__setGPSFrequencyResponse
#define SOAP_TYPE_ns3__setGPSFrequencyResponse (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__setGPSFrequencyResponse(struct soap*, struct ns3__setGPSFrequencyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__setGPSFrequencyResponse(struct soap*, const struct ns3__setGPSFrequencyResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__setGPSFrequencyResponse(struct soap*, const struct ns3__setGPSFrequencyResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__setGPSFrequencyResponse(struct soap*, const char*, int, const struct ns3__setGPSFrequencyResponse *, const char*);
SOAP_FMAC3 struct ns3__setGPSFrequencyResponse * SOAP_FMAC4 soap_get_ns3__setGPSFrequencyResponse(struct soap*, struct ns3__setGPSFrequencyResponse *, const char*, const char*);
SOAP_FMAC3 struct ns3__setGPSFrequencyResponse * SOAP_FMAC4 soap_in_ns3__setGPSFrequencyResponse(struct soap*, const char*, struct ns3__setGPSFrequencyResponse *, const char*);

#ifndef SOAP_TYPE_ns3__sendMessage
#define SOAP_TYPE_ns3__sendMessage (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__sendMessage(struct soap*, struct ns3__sendMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__sendMessage(struct soap*, const struct ns3__sendMessage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__sendMessage(struct soap*, const struct ns3__sendMessage *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__sendMessage(struct soap*, const char*, int, const struct ns3__sendMessage *, const char*);
SOAP_FMAC3 struct ns3__sendMessage * SOAP_FMAC4 soap_get_ns3__sendMessage(struct soap*, struct ns3__sendMessage *, const char*, const char*);
SOAP_FMAC3 struct ns3__sendMessage * SOAP_FMAC4 soap_in_ns3__sendMessage(struct soap*, const char*, struct ns3__sendMessage *, const char*);

#ifndef SOAP_TYPE_ns3__sendMessageResponse
#define SOAP_TYPE_ns3__sendMessageResponse (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__sendMessageResponse(struct soap*, struct ns3__sendMessageResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__sendMessageResponse(struct soap*, const struct ns3__sendMessageResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__sendMessageResponse(struct soap*, const struct ns3__sendMessageResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__sendMessageResponse(struct soap*, const char*, int, const struct ns3__sendMessageResponse *, const char*);
SOAP_FMAC3 struct ns3__sendMessageResponse * SOAP_FMAC4 soap_get_ns3__sendMessageResponse(struct soap*, struct ns3__sendMessageResponse *, const char*, const char*);
SOAP_FMAC3 struct ns3__sendMessageResponse * SOAP_FMAC4 soap_in_ns3__sendMessageResponse(struct soap*, const char*, struct ns3__sendMessageResponse *, const char*);

#ifndef SOAP_TYPE_ns3__queryVersion
#define SOAP_TYPE_ns3__queryVersion (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__queryVersion(struct soap*, struct ns3__queryVersion *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__queryVersion(struct soap*, const struct ns3__queryVersion *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__queryVersion(struct soap*, const struct ns3__queryVersion *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__queryVersion(struct soap*, const char*, int, const struct ns3__queryVersion *, const char*);
SOAP_FMAC3 struct ns3__queryVersion * SOAP_FMAC4 soap_get_ns3__queryVersion(struct soap*, struct ns3__queryVersion *, const char*, const char*);
SOAP_FMAC3 struct ns3__queryVersion * SOAP_FMAC4 soap_in_ns3__queryVersion(struct soap*, const char*, struct ns3__queryVersion *, const char*);

#ifndef SOAP_TYPE_ns3__queryVersionResponse
#define SOAP_TYPE_ns3__queryVersionResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__queryVersionResponse(struct soap*, struct ns3__queryVersionResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__queryVersionResponse(struct soap*, const struct ns3__queryVersionResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__queryVersionResponse(struct soap*, const struct ns3__queryVersionResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__queryVersionResponse(struct soap*, const char*, int, const struct ns3__queryVersionResponse *, const char*);
SOAP_FMAC3 struct ns3__queryVersionResponse * SOAP_FMAC4 soap_get_ns3__queryVersionResponse(struct soap*, struct ns3__queryVersionResponse *, const char*, const char*);
SOAP_FMAC3 struct ns3__queryVersionResponse * SOAP_FMAC4 soap_in_ns3__queryVersionResponse(struct soap*, const char*, struct ns3__queryVersionResponse *, const char*);

#ifndef SOAP_TYPE_ns3__takePhoto
#define SOAP_TYPE_ns3__takePhoto (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__takePhoto(struct soap*, struct ns3__takePhoto *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__takePhoto(struct soap*, const struct ns3__takePhoto *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__takePhoto(struct soap*, const struct ns3__takePhoto *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__takePhoto(struct soap*, const char*, int, const struct ns3__takePhoto *, const char*);
SOAP_FMAC3 struct ns3__takePhoto * SOAP_FMAC4 soap_get_ns3__takePhoto(struct soap*, struct ns3__takePhoto *, const char*, const char*);
SOAP_FMAC3 struct ns3__takePhoto * SOAP_FMAC4 soap_in_ns3__takePhoto(struct soap*, const char*, struct ns3__takePhoto *, const char*);

#ifndef SOAP_TYPE_ns3__takePhotoResponse
#define SOAP_TYPE_ns3__takePhotoResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__takePhotoResponse(struct soap*, struct ns3__takePhotoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__takePhotoResponse(struct soap*, const struct ns3__takePhotoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__takePhotoResponse(struct soap*, const struct ns3__takePhotoResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__takePhotoResponse(struct soap*, const char*, int, const struct ns3__takePhotoResponse *, const char*);
SOAP_FMAC3 struct ns3__takePhotoResponse * SOAP_FMAC4 soap_get_ns3__takePhotoResponse(struct soap*, struct ns3__takePhotoResponse *, const char*, const char*);
SOAP_FMAC3 struct ns3__takePhotoResponse * SOAP_FMAC4 soap_in_ns3__takePhotoResponse(struct soap*, const char*, struct ns3__takePhotoResponse *, const char*);

#ifndef SOAP_TYPE___ns1__sayHello
#define SOAP_TYPE___ns1__sayHello (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__sayHello(struct soap*, struct __ns1__sayHello *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__sayHello(struct soap*, const struct __ns1__sayHello *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__sayHello(struct soap*, const struct __ns1__sayHello *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__sayHello(struct soap*, const char*, int, const struct __ns1__sayHello *, const char*);
SOAP_FMAC3 struct __ns1__sayHello * SOAP_FMAC4 soap_get___ns1__sayHello(struct soap*, struct __ns1__sayHello *, const char*, const char*);
SOAP_FMAC3 struct __ns1__sayHello * SOAP_FMAC4 soap_in___ns1__sayHello(struct soap*, const char*, struct __ns1__sayHello *, const char*);

#ifndef SOAP_TYPE___ns1__OperationCenter
#define SOAP_TYPE___ns1__OperationCenter (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__OperationCenter(struct soap*, struct __ns1__OperationCenter *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__OperationCenter(struct soap*, const struct __ns1__OperationCenter *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__OperationCenter(struct soap*, const struct __ns1__OperationCenter *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__OperationCenter(struct soap*, const char*, int, const struct __ns1__OperationCenter *, const char*);
SOAP_FMAC3 struct __ns1__OperationCenter * SOAP_FMAC4 soap_get___ns1__OperationCenter(struct soap*, struct __ns1__OperationCenter *, const char*, const char*);
SOAP_FMAC3 struct __ns1__OperationCenter * SOAP_FMAC4 soap_in___ns1__OperationCenter(struct soap*, const char*, struct __ns1__OperationCenter *, const char*);

#ifndef SOAP_TYPE___ns1__OperationSms
#define SOAP_TYPE___ns1__OperationSms (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__OperationSms(struct soap*, struct __ns1__OperationSms *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__OperationSms(struct soap*, const struct __ns1__OperationSms *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__OperationSms(struct soap*, const struct __ns1__OperationSms *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__OperationSms(struct soap*, const char*, int, const struct __ns1__OperationSms *, const char*);
SOAP_FMAC3 struct __ns1__OperationSms * SOAP_FMAC4 soap_get___ns1__OperationSms(struct soap*, struct __ns1__OperationSms *, const char*, const char*);
SOAP_FMAC3 struct __ns1__OperationSms * SOAP_FMAC4 soap_in___ns1__OperationSms(struct soap*, const char*, struct __ns1__OperationSms *, const char*);

#ifndef SOAP_TYPE_ns2__UpdateServerInfoResp
#define SOAP_TYPE_ns2__UpdateServerInfoResp (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__UpdateServerInfoResp(struct soap*, struct ns2__UpdateServerInfoResp *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__UpdateServerInfoResp(struct soap*, const struct ns2__UpdateServerInfoResp *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__UpdateServerInfoResp(struct soap*, const struct ns2__UpdateServerInfoResp *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__UpdateServerInfoResp(struct soap*, const char*, int, const struct ns2__UpdateServerInfoResp *, const char*);
SOAP_FMAC3 struct ns2__UpdateServerInfoResp * SOAP_FMAC4 soap_get_ns2__UpdateServerInfoResp(struct soap*, struct ns2__UpdateServerInfoResp *, const char*, const char*);
SOAP_FMAC3 struct ns2__UpdateServerInfoResp * SOAP_FMAC4 soap_in_ns2__UpdateServerInfoResp(struct soap*, const char*, struct ns2__UpdateServerInfoResp *, const char*);

#ifndef SOAP_TYPE_ns2__UpdateServerInfoReq
#define SOAP_TYPE_ns2__UpdateServerInfoReq (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__UpdateServerInfoReq(struct soap*, struct ns2__UpdateServerInfoReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__UpdateServerInfoReq(struct soap*, const struct ns2__UpdateServerInfoReq *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__UpdateServerInfoReq(struct soap*, const struct ns2__UpdateServerInfoReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__UpdateServerInfoReq(struct soap*, const char*, int, const struct ns2__UpdateServerInfoReq *, const char*);
SOAP_FMAC3 struct ns2__UpdateServerInfoReq * SOAP_FMAC4 soap_get_ns2__UpdateServerInfoReq(struct soap*, struct ns2__UpdateServerInfoReq *, const char*, const char*);
SOAP_FMAC3 struct ns2__UpdateServerInfoReq * SOAP_FMAC4 soap_in_ns2__UpdateServerInfoReq(struct soap*, const char*, struct ns2__UpdateServerInfoReq *, const char*);

#ifndef SOAP_TYPE_ns2__UpdateSysConfResp
#define SOAP_TYPE_ns2__UpdateSysConfResp (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__UpdateSysConfResp(struct soap*, struct ns2__UpdateSysConfResp *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__UpdateSysConfResp(struct soap*, const struct ns2__UpdateSysConfResp *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__UpdateSysConfResp(struct soap*, const struct ns2__UpdateSysConfResp *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__UpdateSysConfResp(struct soap*, const char*, int, const struct ns2__UpdateSysConfResp *, const char*);
SOAP_FMAC3 struct ns2__UpdateSysConfResp * SOAP_FMAC4 soap_get_ns2__UpdateSysConfResp(struct soap*, struct ns2__UpdateSysConfResp *, const char*, const char*);
SOAP_FMAC3 struct ns2__UpdateSysConfResp * SOAP_FMAC4 soap_in_ns2__UpdateSysConfResp(struct soap*, const char*, struct ns2__UpdateSysConfResp *, const char*);

#ifndef SOAP_TYPE_ns2__UpdateSysConfReq
#define SOAP_TYPE_ns2__UpdateSysConfReq (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__UpdateSysConfReq(struct soap*, struct ns2__UpdateSysConfReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__UpdateSysConfReq(struct soap*, const struct ns2__UpdateSysConfReq *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__UpdateSysConfReq(struct soap*, const struct ns2__UpdateSysConfReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__UpdateSysConfReq(struct soap*, const char*, int, const struct ns2__UpdateSysConfReq *, const char*);
SOAP_FMAC3 struct ns2__UpdateSysConfReq * SOAP_FMAC4 soap_get_ns2__UpdateSysConfReq(struct soap*, struct ns2__UpdateSysConfReq *, const char*, const char*);
SOAP_FMAC3 struct ns2__UpdateSysConfReq * SOAP_FMAC4 soap_in_ns2__UpdateSysConfReq(struct soap*, const char*, struct ns2__UpdateSysConfReq *, const char*);

#ifndef SOAP_TYPE_ns2__SetMileageResp
#define SOAP_TYPE_ns2__SetMileageResp (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__SetMileageResp(struct soap*, struct ns2__SetMileageResp *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__SetMileageResp(struct soap*, const struct ns2__SetMileageResp *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__SetMileageResp(struct soap*, const struct ns2__SetMileageResp *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__SetMileageResp(struct soap*, const char*, int, const struct ns2__SetMileageResp *, const char*);
SOAP_FMAC3 struct ns2__SetMileageResp * SOAP_FMAC4 soap_get_ns2__SetMileageResp(struct soap*, struct ns2__SetMileageResp *, const char*, const char*);
SOAP_FMAC3 struct ns2__SetMileageResp * SOAP_FMAC4 soap_in_ns2__SetMileageResp(struct soap*, const char*, struct ns2__SetMileageResp *, const char*);

#ifndef SOAP_TYPE_ns2__SetMileageReq
#define SOAP_TYPE_ns2__SetMileageReq (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__SetMileageReq(struct soap*, struct ns2__SetMileageReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__SetMileageReq(struct soap*, const struct ns2__SetMileageReq *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__SetMileageReq(struct soap*, const struct ns2__SetMileageReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__SetMileageReq(struct soap*, const char*, int, const struct ns2__SetMileageReq *, const char*);
SOAP_FMAC3 struct ns2__SetMileageReq * SOAP_FMAC4 soap_get_ns2__SetMileageReq(struct soap*, struct ns2__SetMileageReq *, const char*, const char*);
SOAP_FMAC3 struct ns2__SetMileageReq * SOAP_FMAC4 soap_in_ns2__SetMileageReq(struct soap*, const char*, struct ns2__SetMileageReq *, const char*);

#ifndef SOAP_TYPE_ns2__SetGPSFrequencyResp
#define SOAP_TYPE_ns2__SetGPSFrequencyResp (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__SetGPSFrequencyResp(struct soap*, struct ns2__SetGPSFrequencyResp *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__SetGPSFrequencyResp(struct soap*, const struct ns2__SetGPSFrequencyResp *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__SetGPSFrequencyResp(struct soap*, const struct ns2__SetGPSFrequencyResp *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__SetGPSFrequencyResp(struct soap*, const char*, int, const struct ns2__SetGPSFrequencyResp *, const char*);
SOAP_FMAC3 struct ns2__SetGPSFrequencyResp * SOAP_FMAC4 soap_get_ns2__SetGPSFrequencyResp(struct soap*, struct ns2__SetGPSFrequencyResp *, const char*, const char*);
SOAP_FMAC3 struct ns2__SetGPSFrequencyResp * SOAP_FMAC4 soap_in_ns2__SetGPSFrequencyResp(struct soap*, const char*, struct ns2__SetGPSFrequencyResp *, const char*);

#ifndef SOAP_TYPE_ns2__SetGPSFrequencyReq
#define SOAP_TYPE_ns2__SetGPSFrequencyReq (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__SetGPSFrequencyReq(struct soap*, struct ns2__SetGPSFrequencyReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__SetGPSFrequencyReq(struct soap*, const struct ns2__SetGPSFrequencyReq *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__SetGPSFrequencyReq(struct soap*, const struct ns2__SetGPSFrequencyReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__SetGPSFrequencyReq(struct soap*, const char*, int, const struct ns2__SetGPSFrequencyReq *, const char*);
SOAP_FMAC3 struct ns2__SetGPSFrequencyReq * SOAP_FMAC4 soap_get_ns2__SetGPSFrequencyReq(struct soap*, struct ns2__SetGPSFrequencyReq *, const char*, const char*);
SOAP_FMAC3 struct ns2__SetGPSFrequencyReq * SOAP_FMAC4 soap_in_ns2__SetGPSFrequencyReq(struct soap*, const char*, struct ns2__SetGPSFrequencyReq *, const char*);

#ifndef SOAP_TYPE_ns2__SendMsgResp
#define SOAP_TYPE_ns2__SendMsgResp (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__SendMsgResp(struct soap*, struct ns2__SendMsgResp *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__SendMsgResp(struct soap*, const struct ns2__SendMsgResp *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__SendMsgResp(struct soap*, const struct ns2__SendMsgResp *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__SendMsgResp(struct soap*, const char*, int, const struct ns2__SendMsgResp *, const char*);
SOAP_FMAC3 struct ns2__SendMsgResp * SOAP_FMAC4 soap_get_ns2__SendMsgResp(struct soap*, struct ns2__SendMsgResp *, const char*, const char*);
SOAP_FMAC3 struct ns2__SendMsgResp * SOAP_FMAC4 soap_in_ns2__SendMsgResp(struct soap*, const char*, struct ns2__SendMsgResp *, const char*);

#ifndef SOAP_TYPE_ns2__SendMsgReq
#define SOAP_TYPE_ns2__SendMsgReq (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__SendMsgReq(struct soap*, struct ns2__SendMsgReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__SendMsgReq(struct soap*, const struct ns2__SendMsgReq *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__SendMsgReq(struct soap*, const struct ns2__SendMsgReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__SendMsgReq(struct soap*, const char*, int, const struct ns2__SendMsgReq *, const char*);
SOAP_FMAC3 struct ns2__SendMsgReq * SOAP_FMAC4 soap_get_ns2__SendMsgReq(struct soap*, struct ns2__SendMsgReq *, const char*, const char*);
SOAP_FMAC3 struct ns2__SendMsgReq * SOAP_FMAC4 soap_in_ns2__SendMsgReq(struct soap*, const char*, struct ns2__SendMsgReq *, const char*);

#ifndef SOAP_TYPE_ns2__QueryVerResp
#define SOAP_TYPE_ns2__QueryVerResp (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__QueryVerResp(struct soap*, struct ns2__QueryVerResp *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__QueryVerResp(struct soap*, const struct ns2__QueryVerResp *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__QueryVerResp(struct soap*, const struct ns2__QueryVerResp *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__QueryVerResp(struct soap*, const char*, int, const struct ns2__QueryVerResp *, const char*);
SOAP_FMAC3 struct ns2__QueryVerResp * SOAP_FMAC4 soap_get_ns2__QueryVerResp(struct soap*, struct ns2__QueryVerResp *, const char*, const char*);
SOAP_FMAC3 struct ns2__QueryVerResp * SOAP_FMAC4 soap_in_ns2__QueryVerResp(struct soap*, const char*, struct ns2__QueryVerResp *, const char*);

#ifndef SOAP_TYPE_ns2__QueryVerReq
#define SOAP_TYPE_ns2__QueryVerReq (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__QueryVerReq(struct soap*, struct ns2__QueryVerReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__QueryVerReq(struct soap*, const struct ns2__QueryVerReq *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__QueryVerReq(struct soap*, const struct ns2__QueryVerReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__QueryVerReq(struct soap*, const char*, int, const struct ns2__QueryVerReq *, const char*);
SOAP_FMAC3 struct ns2__QueryVerReq * SOAP_FMAC4 soap_get_ns2__QueryVerReq(struct soap*, struct ns2__QueryVerReq *, const char*, const char*);
SOAP_FMAC3 struct ns2__QueryVerReq * SOAP_FMAC4 soap_in_ns2__QueryVerReq(struct soap*, const char*, struct ns2__QueryVerReq *, const char*);

#ifndef SOAP_TYPE_ns2__TakePhotoResp
#define SOAP_TYPE_ns2__TakePhotoResp (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__TakePhotoResp(struct soap*, struct ns2__TakePhotoResp *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__TakePhotoResp(struct soap*, const struct ns2__TakePhotoResp *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__TakePhotoResp(struct soap*, const struct ns2__TakePhotoResp *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__TakePhotoResp(struct soap*, const char*, int, const struct ns2__TakePhotoResp *, const char*);
SOAP_FMAC3 struct ns2__TakePhotoResp * SOAP_FMAC4 soap_get_ns2__TakePhotoResp(struct soap*, struct ns2__TakePhotoResp *, const char*, const char*);
SOAP_FMAC3 struct ns2__TakePhotoResp * SOAP_FMAC4 soap_in_ns2__TakePhotoResp(struct soap*, const char*, struct ns2__TakePhotoResp *, const char*);

#ifndef SOAP_TYPE_ns2__TakePhotoReq
#define SOAP_TYPE_ns2__TakePhotoReq (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__TakePhotoReq(struct soap*, struct ns2__TakePhotoReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__TakePhotoReq(struct soap*, const struct ns2__TakePhotoReq *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__TakePhotoReq(struct soap*, const struct ns2__TakePhotoReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__TakePhotoReq(struct soap*, const char*, int, const struct ns2__TakePhotoReq *, const char*);
SOAP_FMAC3 struct ns2__TakePhotoReq * SOAP_FMAC4 soap_get_ns2__TakePhotoReq(struct soap*, struct ns2__TakePhotoReq *, const char*, const char*);
SOAP_FMAC3 struct ns2__TakePhotoReq * SOAP_FMAC4 soap_in_ns2__TakePhotoReq(struct soap*, const char*, struct ns2__TakePhotoReq *, const char*);

#ifndef SOAP_TYPE__ns1__sayHelloResponse
#define SOAP_TYPE__ns1__sayHelloResponse (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__sayHelloResponse(struct soap*, struct _ns1__sayHelloResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__sayHelloResponse(struct soap*, const struct _ns1__sayHelloResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__sayHelloResponse(struct soap*, const struct _ns1__sayHelloResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__sayHelloResponse(struct soap*, const char*, int, const struct _ns1__sayHelloResponse *, const char*);
SOAP_FMAC3 struct _ns1__sayHelloResponse * SOAP_FMAC4 soap_get__ns1__sayHelloResponse(struct soap*, struct _ns1__sayHelloResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__sayHelloResponse * SOAP_FMAC4 soap_in__ns1__sayHelloResponse(struct soap*, const char*, struct _ns1__sayHelloResponse *, const char*);

#ifndef SOAP_TYPE__ns1__sayHello
#define SOAP_TYPE__ns1__sayHello (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__sayHello(struct soap*, struct _ns1__sayHello *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__sayHello(struct soap*, const struct _ns1__sayHello *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__sayHello(struct soap*, const struct _ns1__sayHello *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__sayHello(struct soap*, const char*, int, const struct _ns1__sayHello *, const char*);
SOAP_FMAC3 struct _ns1__sayHello * SOAP_FMAC4 soap_get__ns1__sayHello(struct soap*, struct _ns1__sayHello *, const char*, const char*);
SOAP_FMAC3 struct _ns1__sayHello * SOAP_FMAC4 soap_in__ns1__sayHello(struct soap*, const char*, struct _ns1__sayHello *, const char*);

#ifndef SOAP_TYPE__ns1__OperationCenterResponse
#define SOAP_TYPE__ns1__OperationCenterResponse (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__OperationCenterResponse(struct soap*, struct _ns1__OperationCenterResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__OperationCenterResponse(struct soap*, const struct _ns1__OperationCenterResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__OperationCenterResponse(struct soap*, const struct _ns1__OperationCenterResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__OperationCenterResponse(struct soap*, const char*, int, const struct _ns1__OperationCenterResponse *, const char*);
SOAP_FMAC3 struct _ns1__OperationCenterResponse * SOAP_FMAC4 soap_get__ns1__OperationCenterResponse(struct soap*, struct _ns1__OperationCenterResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__OperationCenterResponse * SOAP_FMAC4 soap_in__ns1__OperationCenterResponse(struct soap*, const char*, struct _ns1__OperationCenterResponse *, const char*);

#ifndef SOAP_TYPE__ns1__OperationCenter
#define SOAP_TYPE__ns1__OperationCenter (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__OperationCenter(struct soap*, struct _ns1__OperationCenter *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__OperationCenter(struct soap*, const struct _ns1__OperationCenter *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__OperationCenter(struct soap*, const struct _ns1__OperationCenter *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__OperationCenter(struct soap*, const char*, int, const struct _ns1__OperationCenter *, const char*);
SOAP_FMAC3 struct _ns1__OperationCenter * SOAP_FMAC4 soap_get__ns1__OperationCenter(struct soap*, struct _ns1__OperationCenter *, const char*, const char*);
SOAP_FMAC3 struct _ns1__OperationCenter * SOAP_FMAC4 soap_in__ns1__OperationCenter(struct soap*, const char*, struct _ns1__OperationCenter *, const char*);

#ifndef SOAP_TYPE__ns1__OperationSmsResponse
#define SOAP_TYPE__ns1__OperationSmsResponse (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__OperationSmsResponse(struct soap*, struct _ns1__OperationSmsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__OperationSmsResponse(struct soap*, const struct _ns1__OperationSmsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__OperationSmsResponse(struct soap*, const struct _ns1__OperationSmsResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__OperationSmsResponse(struct soap*, const char*, int, const struct _ns1__OperationSmsResponse *, const char*);
SOAP_FMAC3 struct _ns1__OperationSmsResponse * SOAP_FMAC4 soap_get__ns1__OperationSmsResponse(struct soap*, struct _ns1__OperationSmsResponse *, const char*, const char*);
SOAP_FMAC3 struct _ns1__OperationSmsResponse * SOAP_FMAC4 soap_in__ns1__OperationSmsResponse(struct soap*, const char*, struct _ns1__OperationSmsResponse *, const char*);

#ifndef SOAP_TYPE__ns1__OperationSms
#define SOAP_TYPE__ns1__OperationSms (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__ns1__OperationSms(struct soap*, struct _ns1__OperationSms *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__ns1__OperationSms(struct soap*, const struct _ns1__OperationSms *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__ns1__OperationSms(struct soap*, const struct _ns1__OperationSms *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__OperationSms(struct soap*, const char*, int, const struct _ns1__OperationSms *, const char*);
SOAP_FMAC3 struct _ns1__OperationSms * SOAP_FMAC4 soap_get__ns1__OperationSms(struct soap*, struct _ns1__OperationSms *, const char*, const char*);
SOAP_FMAC3 struct _ns1__OperationSms * SOAP_FMAC4 soap_in__ns1__OperationSms(struct soap*, const char*, struct _ns1__OperationSms *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (90)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons3__updateServerInfoResponse
#define SOAP_TYPE_PointerTons3__updateServerInfoResponse (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__updateServerInfoResponse(struct soap*, struct ns3__updateServerInfoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__updateServerInfoResponse(struct soap*, struct ns3__updateServerInfoResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__updateServerInfoResponse(struct soap*, const char *, int, struct ns3__updateServerInfoResponse *const*, const char *);
SOAP_FMAC3 struct ns3__updateServerInfoResponse ** SOAP_FMAC4 soap_get_PointerTons3__updateServerInfoResponse(struct soap*, struct ns3__updateServerInfoResponse **, const char*, const char*);
SOAP_FMAC3 struct ns3__updateServerInfoResponse ** SOAP_FMAC4 soap_in_PointerTons3__updateServerInfoResponse(struct soap*, const char*, struct ns3__updateServerInfoResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons2__UpdateServerInfoReq
#define SOAP_TYPE_PointerTons2__UpdateServerInfoReq (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__UpdateServerInfoReq(struct soap*, struct ns2__UpdateServerInfoReq *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__UpdateServerInfoReq(struct soap*, struct ns2__UpdateServerInfoReq *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__UpdateServerInfoReq(struct soap*, const char *, int, struct ns2__UpdateServerInfoReq *const*, const char *);
SOAP_FMAC3 struct ns2__UpdateServerInfoReq ** SOAP_FMAC4 soap_get_PointerTons2__UpdateServerInfoReq(struct soap*, struct ns2__UpdateServerInfoReq **, const char*, const char*);
SOAP_FMAC3 struct ns2__UpdateServerInfoReq ** SOAP_FMAC4 soap_in_PointerTons2__UpdateServerInfoReq(struct soap*, const char*, struct ns2__UpdateServerInfoReq **, const char*);

#ifndef SOAP_TYPE_PointerTons2__UpdateServerInfoResp
#define SOAP_TYPE_PointerTons2__UpdateServerInfoResp (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__UpdateServerInfoResp(struct soap*, struct ns2__UpdateServerInfoResp *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__UpdateServerInfoResp(struct soap*, struct ns2__UpdateServerInfoResp *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__UpdateServerInfoResp(struct soap*, const char *, int, struct ns2__UpdateServerInfoResp *const*, const char *);
SOAP_FMAC3 struct ns2__UpdateServerInfoResp ** SOAP_FMAC4 soap_get_PointerTons2__UpdateServerInfoResp(struct soap*, struct ns2__UpdateServerInfoResp **, const char*, const char*);
SOAP_FMAC3 struct ns2__UpdateServerInfoResp ** SOAP_FMAC4 soap_in_PointerTons2__UpdateServerInfoResp(struct soap*, const char*, struct ns2__UpdateServerInfoResp **, const char*);

#ifndef SOAP_TYPE_PointerTons3__updateSysConfResponse
#define SOAP_TYPE_PointerTons3__updateSysConfResponse (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__updateSysConfResponse(struct soap*, struct ns3__updateSysConfResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__updateSysConfResponse(struct soap*, struct ns3__updateSysConfResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__updateSysConfResponse(struct soap*, const char *, int, struct ns3__updateSysConfResponse *const*, const char *);
SOAP_FMAC3 struct ns3__updateSysConfResponse ** SOAP_FMAC4 soap_get_PointerTons3__updateSysConfResponse(struct soap*, struct ns3__updateSysConfResponse **, const char*, const char*);
SOAP_FMAC3 struct ns3__updateSysConfResponse ** SOAP_FMAC4 soap_in_PointerTons3__updateSysConfResponse(struct soap*, const char*, struct ns3__updateSysConfResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons2__UpdateSysConfReq
#define SOAP_TYPE_PointerTons2__UpdateSysConfReq (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__UpdateSysConfReq(struct soap*, struct ns2__UpdateSysConfReq *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__UpdateSysConfReq(struct soap*, struct ns2__UpdateSysConfReq *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__UpdateSysConfReq(struct soap*, const char *, int, struct ns2__UpdateSysConfReq *const*, const char *);
SOAP_FMAC3 struct ns2__UpdateSysConfReq ** SOAP_FMAC4 soap_get_PointerTons2__UpdateSysConfReq(struct soap*, struct ns2__UpdateSysConfReq **, const char*, const char*);
SOAP_FMAC3 struct ns2__UpdateSysConfReq ** SOAP_FMAC4 soap_in_PointerTons2__UpdateSysConfReq(struct soap*, const char*, struct ns2__UpdateSysConfReq **, const char*);

#ifndef SOAP_TYPE_PointerTons2__UpdateSysConfResp
#define SOAP_TYPE_PointerTons2__UpdateSysConfResp (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__UpdateSysConfResp(struct soap*, struct ns2__UpdateSysConfResp *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__UpdateSysConfResp(struct soap*, struct ns2__UpdateSysConfResp *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__UpdateSysConfResp(struct soap*, const char *, int, struct ns2__UpdateSysConfResp *const*, const char *);
SOAP_FMAC3 struct ns2__UpdateSysConfResp ** SOAP_FMAC4 soap_get_PointerTons2__UpdateSysConfResp(struct soap*, struct ns2__UpdateSysConfResp **, const char*, const char*);
SOAP_FMAC3 struct ns2__UpdateSysConfResp ** SOAP_FMAC4 soap_in_PointerTons2__UpdateSysConfResp(struct soap*, const char*, struct ns2__UpdateSysConfResp **, const char*);

#ifndef SOAP_TYPE_PointerTons3__setMileageResponse
#define SOAP_TYPE_PointerTons3__setMileageResponse (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__setMileageResponse(struct soap*, struct ns3__setMileageResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__setMileageResponse(struct soap*, struct ns3__setMileageResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__setMileageResponse(struct soap*, const char *, int, struct ns3__setMileageResponse *const*, const char *);
SOAP_FMAC3 struct ns3__setMileageResponse ** SOAP_FMAC4 soap_get_PointerTons3__setMileageResponse(struct soap*, struct ns3__setMileageResponse **, const char*, const char*);
SOAP_FMAC3 struct ns3__setMileageResponse ** SOAP_FMAC4 soap_in_PointerTons3__setMileageResponse(struct soap*, const char*, struct ns3__setMileageResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons2__SetMileageReq
#define SOAP_TYPE_PointerTons2__SetMileageReq (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__SetMileageReq(struct soap*, struct ns2__SetMileageReq *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__SetMileageReq(struct soap*, struct ns2__SetMileageReq *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__SetMileageReq(struct soap*, const char *, int, struct ns2__SetMileageReq *const*, const char *);
SOAP_FMAC3 struct ns2__SetMileageReq ** SOAP_FMAC4 soap_get_PointerTons2__SetMileageReq(struct soap*, struct ns2__SetMileageReq **, const char*, const char*);
SOAP_FMAC3 struct ns2__SetMileageReq ** SOAP_FMAC4 soap_in_PointerTons2__SetMileageReq(struct soap*, const char*, struct ns2__SetMileageReq **, const char*);

#ifndef SOAP_TYPE_PointerTons2__SetMileageResp
#define SOAP_TYPE_PointerTons2__SetMileageResp (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__SetMileageResp(struct soap*, struct ns2__SetMileageResp *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__SetMileageResp(struct soap*, struct ns2__SetMileageResp *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__SetMileageResp(struct soap*, const char *, int, struct ns2__SetMileageResp *const*, const char *);
SOAP_FMAC3 struct ns2__SetMileageResp ** SOAP_FMAC4 soap_get_PointerTons2__SetMileageResp(struct soap*, struct ns2__SetMileageResp **, const char*, const char*);
SOAP_FMAC3 struct ns2__SetMileageResp ** SOAP_FMAC4 soap_in_PointerTons2__SetMileageResp(struct soap*, const char*, struct ns2__SetMileageResp **, const char*);

#ifndef SOAP_TYPE_PointerTons3__setGPSFrequencyResponse
#define SOAP_TYPE_PointerTons3__setGPSFrequencyResponse (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__setGPSFrequencyResponse(struct soap*, struct ns3__setGPSFrequencyResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__setGPSFrequencyResponse(struct soap*, struct ns3__setGPSFrequencyResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__setGPSFrequencyResponse(struct soap*, const char *, int, struct ns3__setGPSFrequencyResponse *const*, const char *);
SOAP_FMAC3 struct ns3__setGPSFrequencyResponse ** SOAP_FMAC4 soap_get_PointerTons3__setGPSFrequencyResponse(struct soap*, struct ns3__setGPSFrequencyResponse **, const char*, const char*);
SOAP_FMAC3 struct ns3__setGPSFrequencyResponse ** SOAP_FMAC4 soap_in_PointerTons3__setGPSFrequencyResponse(struct soap*, const char*, struct ns3__setGPSFrequencyResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons2__SetGPSFrequencyReq
#define SOAP_TYPE_PointerTons2__SetGPSFrequencyReq (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__SetGPSFrequencyReq(struct soap*, struct ns2__SetGPSFrequencyReq *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__SetGPSFrequencyReq(struct soap*, struct ns2__SetGPSFrequencyReq *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__SetGPSFrequencyReq(struct soap*, const char *, int, struct ns2__SetGPSFrequencyReq *const*, const char *);
SOAP_FMAC3 struct ns2__SetGPSFrequencyReq ** SOAP_FMAC4 soap_get_PointerTons2__SetGPSFrequencyReq(struct soap*, struct ns2__SetGPSFrequencyReq **, const char*, const char*);
SOAP_FMAC3 struct ns2__SetGPSFrequencyReq ** SOAP_FMAC4 soap_in_PointerTons2__SetGPSFrequencyReq(struct soap*, const char*, struct ns2__SetGPSFrequencyReq **, const char*);

#ifndef SOAP_TYPE_PointerTons2__SetGPSFrequencyResp
#define SOAP_TYPE_PointerTons2__SetGPSFrequencyResp (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__SetGPSFrequencyResp(struct soap*, struct ns2__SetGPSFrequencyResp *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__SetGPSFrequencyResp(struct soap*, struct ns2__SetGPSFrequencyResp *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__SetGPSFrequencyResp(struct soap*, const char *, int, struct ns2__SetGPSFrequencyResp *const*, const char *);
SOAP_FMAC3 struct ns2__SetGPSFrequencyResp ** SOAP_FMAC4 soap_get_PointerTons2__SetGPSFrequencyResp(struct soap*, struct ns2__SetGPSFrequencyResp **, const char*, const char*);
SOAP_FMAC3 struct ns2__SetGPSFrequencyResp ** SOAP_FMAC4 soap_in_PointerTons2__SetGPSFrequencyResp(struct soap*, const char*, struct ns2__SetGPSFrequencyResp **, const char*);

#ifndef SOAP_TYPE_PointerTons3__sendMessageResponse
#define SOAP_TYPE_PointerTons3__sendMessageResponse (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__sendMessageResponse(struct soap*, struct ns3__sendMessageResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__sendMessageResponse(struct soap*, struct ns3__sendMessageResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__sendMessageResponse(struct soap*, const char *, int, struct ns3__sendMessageResponse *const*, const char *);
SOAP_FMAC3 struct ns3__sendMessageResponse ** SOAP_FMAC4 soap_get_PointerTons3__sendMessageResponse(struct soap*, struct ns3__sendMessageResponse **, const char*, const char*);
SOAP_FMAC3 struct ns3__sendMessageResponse ** SOAP_FMAC4 soap_in_PointerTons3__sendMessageResponse(struct soap*, const char*, struct ns3__sendMessageResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons2__SendMsgReq
#define SOAP_TYPE_PointerTons2__SendMsgReq (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__SendMsgReq(struct soap*, struct ns2__SendMsgReq *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__SendMsgReq(struct soap*, struct ns2__SendMsgReq *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__SendMsgReq(struct soap*, const char *, int, struct ns2__SendMsgReq *const*, const char *);
SOAP_FMAC3 struct ns2__SendMsgReq ** SOAP_FMAC4 soap_get_PointerTons2__SendMsgReq(struct soap*, struct ns2__SendMsgReq **, const char*, const char*);
SOAP_FMAC3 struct ns2__SendMsgReq ** SOAP_FMAC4 soap_in_PointerTons2__SendMsgReq(struct soap*, const char*, struct ns2__SendMsgReq **, const char*);

#ifndef SOAP_TYPE_PointerTons2__SendMsgResp
#define SOAP_TYPE_PointerTons2__SendMsgResp (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__SendMsgResp(struct soap*, struct ns2__SendMsgResp *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__SendMsgResp(struct soap*, struct ns2__SendMsgResp *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__SendMsgResp(struct soap*, const char *, int, struct ns2__SendMsgResp *const*, const char *);
SOAP_FMAC3 struct ns2__SendMsgResp ** SOAP_FMAC4 soap_get_PointerTons2__SendMsgResp(struct soap*, struct ns2__SendMsgResp **, const char*, const char*);
SOAP_FMAC3 struct ns2__SendMsgResp ** SOAP_FMAC4 soap_in_PointerTons2__SendMsgResp(struct soap*, const char*, struct ns2__SendMsgResp **, const char*);

#ifndef SOAP_TYPE_PointerTons3__queryVersionResponse
#define SOAP_TYPE_PointerTons3__queryVersionResponse (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__queryVersionResponse(struct soap*, struct ns3__queryVersionResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__queryVersionResponse(struct soap*, struct ns3__queryVersionResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__queryVersionResponse(struct soap*, const char *, int, struct ns3__queryVersionResponse *const*, const char *);
SOAP_FMAC3 struct ns3__queryVersionResponse ** SOAP_FMAC4 soap_get_PointerTons3__queryVersionResponse(struct soap*, struct ns3__queryVersionResponse **, const char*, const char*);
SOAP_FMAC3 struct ns3__queryVersionResponse ** SOAP_FMAC4 soap_in_PointerTons3__queryVersionResponse(struct soap*, const char*, struct ns3__queryVersionResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons2__QueryVerReq
#define SOAP_TYPE_PointerTons2__QueryVerReq (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__QueryVerReq(struct soap*, struct ns2__QueryVerReq *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__QueryVerReq(struct soap*, struct ns2__QueryVerReq *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__QueryVerReq(struct soap*, const char *, int, struct ns2__QueryVerReq *const*, const char *);
SOAP_FMAC3 struct ns2__QueryVerReq ** SOAP_FMAC4 soap_get_PointerTons2__QueryVerReq(struct soap*, struct ns2__QueryVerReq **, const char*, const char*);
SOAP_FMAC3 struct ns2__QueryVerReq ** SOAP_FMAC4 soap_in_PointerTons2__QueryVerReq(struct soap*, const char*, struct ns2__QueryVerReq **, const char*);

#ifndef SOAP_TYPE_PointerTons2__QueryVerResp
#define SOAP_TYPE_PointerTons2__QueryVerResp (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__QueryVerResp(struct soap*, struct ns2__QueryVerResp *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__QueryVerResp(struct soap*, struct ns2__QueryVerResp *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__QueryVerResp(struct soap*, const char *, int, struct ns2__QueryVerResp *const*, const char *);
SOAP_FMAC3 struct ns2__QueryVerResp ** SOAP_FMAC4 soap_get_PointerTons2__QueryVerResp(struct soap*, struct ns2__QueryVerResp **, const char*, const char*);
SOAP_FMAC3 struct ns2__QueryVerResp ** SOAP_FMAC4 soap_in_PointerTons2__QueryVerResp(struct soap*, const char*, struct ns2__QueryVerResp **, const char*);

#ifndef SOAP_TYPE_PointerTons3__takePhotoResponse
#define SOAP_TYPE_PointerTons3__takePhotoResponse (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__takePhotoResponse(struct soap*, struct ns3__takePhotoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__takePhotoResponse(struct soap*, struct ns3__takePhotoResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__takePhotoResponse(struct soap*, const char *, int, struct ns3__takePhotoResponse *const*, const char *);
SOAP_FMAC3 struct ns3__takePhotoResponse ** SOAP_FMAC4 soap_get_PointerTons3__takePhotoResponse(struct soap*, struct ns3__takePhotoResponse **, const char*, const char*);
SOAP_FMAC3 struct ns3__takePhotoResponse ** SOAP_FMAC4 soap_in_PointerTons3__takePhotoResponse(struct soap*, const char*, struct ns3__takePhotoResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons2__TakePhotoReq
#define SOAP_TYPE_PointerTons2__TakePhotoReq (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__TakePhotoReq(struct soap*, struct ns2__TakePhotoReq *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__TakePhotoReq(struct soap*, struct ns2__TakePhotoReq *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__TakePhotoReq(struct soap*, const char *, int, struct ns2__TakePhotoReq *const*, const char *);
SOAP_FMAC3 struct ns2__TakePhotoReq ** SOAP_FMAC4 soap_get_PointerTons2__TakePhotoReq(struct soap*, struct ns2__TakePhotoReq **, const char*, const char*);
SOAP_FMAC3 struct ns2__TakePhotoReq ** SOAP_FMAC4 soap_in_PointerTons2__TakePhotoReq(struct soap*, const char*, struct ns2__TakePhotoReq **, const char*);

#ifndef SOAP_TYPE_PointerTons2__TakePhotoResp
#define SOAP_TYPE_PointerTons2__TakePhotoResp (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__TakePhotoResp(struct soap*, struct ns2__TakePhotoResp *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__TakePhotoResp(struct soap*, struct ns2__TakePhotoResp *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__TakePhotoResp(struct soap*, const char *, int, struct ns2__TakePhotoResp *const*, const char *);
SOAP_FMAC3 struct ns2__TakePhotoResp ** SOAP_FMAC4 soap_get_PointerTons2__TakePhotoResp(struct soap*, struct ns2__TakePhotoResp **, const char*, const char*);
SOAP_FMAC3 struct ns2__TakePhotoResp ** SOAP_FMAC4 soap_in_PointerTons2__TakePhotoResp(struct soap*, const char*, struct ns2__TakePhotoResp **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__sayHelloResponse
#define SOAP_TYPE_PointerTo_ns1__sayHelloResponse (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__sayHelloResponse(struct soap*, struct _ns1__sayHelloResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__sayHelloResponse(struct soap*, struct _ns1__sayHelloResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__sayHelloResponse(struct soap*, const char *, int, struct _ns1__sayHelloResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__sayHelloResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__sayHelloResponse(struct soap*, struct _ns1__sayHelloResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__sayHelloResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__sayHelloResponse(struct soap*, const char*, struct _ns1__sayHelloResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__sayHello
#define SOAP_TYPE_PointerTo_ns1__sayHello (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__sayHello(struct soap*, struct _ns1__sayHello *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__sayHello(struct soap*, struct _ns1__sayHello *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__sayHello(struct soap*, const char *, int, struct _ns1__sayHello *const*, const char *);
SOAP_FMAC3 struct _ns1__sayHello ** SOAP_FMAC4 soap_get_PointerTo_ns1__sayHello(struct soap*, struct _ns1__sayHello **, const char*, const char*);
SOAP_FMAC3 struct _ns1__sayHello ** SOAP_FMAC4 soap_in_PointerTo_ns1__sayHello(struct soap*, const char*, struct _ns1__sayHello **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__OperationCenterResponse
#define SOAP_TYPE_PointerTo_ns1__OperationCenterResponse (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__OperationCenterResponse(struct soap*, struct _ns1__OperationCenterResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__OperationCenterResponse(struct soap*, struct _ns1__OperationCenterResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__OperationCenterResponse(struct soap*, const char *, int, struct _ns1__OperationCenterResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__OperationCenterResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__OperationCenterResponse(struct soap*, struct _ns1__OperationCenterResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__OperationCenterResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__OperationCenterResponse(struct soap*, const char*, struct _ns1__OperationCenterResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__OperationCenter
#define SOAP_TYPE_PointerTo_ns1__OperationCenter (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__OperationCenter(struct soap*, struct _ns1__OperationCenter *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__OperationCenter(struct soap*, struct _ns1__OperationCenter *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__OperationCenter(struct soap*, const char *, int, struct _ns1__OperationCenter *const*, const char *);
SOAP_FMAC3 struct _ns1__OperationCenter ** SOAP_FMAC4 soap_get_PointerTo_ns1__OperationCenter(struct soap*, struct _ns1__OperationCenter **, const char*, const char*);
SOAP_FMAC3 struct _ns1__OperationCenter ** SOAP_FMAC4 soap_in_PointerTo_ns1__OperationCenter(struct soap*, const char*, struct _ns1__OperationCenter **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__OperationSmsResponse
#define SOAP_TYPE_PointerTo_ns1__OperationSmsResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__OperationSmsResponse(struct soap*, struct _ns1__OperationSmsResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__OperationSmsResponse(struct soap*, struct _ns1__OperationSmsResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__OperationSmsResponse(struct soap*, const char *, int, struct _ns1__OperationSmsResponse *const*, const char *);
SOAP_FMAC3 struct _ns1__OperationSmsResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__OperationSmsResponse(struct soap*, struct _ns1__OperationSmsResponse **, const char*, const char*);
SOAP_FMAC3 struct _ns1__OperationSmsResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__OperationSmsResponse(struct soap*, const char*, struct _ns1__OperationSmsResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__OperationSms
#define SOAP_TYPE_PointerTo_ns1__OperationSms (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__OperationSms(struct soap*, struct _ns1__OperationSms *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__OperationSms(struct soap*, struct _ns1__OperationSms *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__OperationSms(struct soap*, const char *, int, struct _ns1__OperationSms *const*, const char *);
SOAP_FMAC3 struct _ns1__OperationSms ** SOAP_FMAC4 soap_get_PointerTo_ns1__OperationSms(struct soap*, struct _ns1__OperationSms **, const char*, const char*);
SOAP_FMAC3 struct _ns1__OperationSms ** SOAP_FMAC4 soap_in_PointerTo_ns1__OperationSms(struct soap*, const char*, struct _ns1__OperationSms **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
